/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citbyui260.section03.battleship.frames;
import citbyui260.section03.battleship.control.*;
/**
 *
 * @author Jeffry Simpson
 */
public class HelpFrame extends javax.swing.JFrame
{
    private final HelpMenuControl helpMenuCommands;
    /**
     * Creates new form HelpFrame
     */
    public HelpFrame()
    {
        initComponents();
        helpMenuCommands = new HelpMenuControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jpBody = new javax.swing.JPanel();
        jpTitle1 = new javax.swing.JPanel();
        jltitle1 = new javax.swing.JLabel();
        jpMenuItems = new javax.swing.JPanel();
        boardHelpBtn = new javax.swing.JButton();
        playersHelpBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        gamePlayingHelpBtn = new javax.swing.JButton();
        hitHelpBtn = new javax.swing.JButton();
        shipHelpBtn = new javax.swing.JButton();
        winningHelpBtn = new javax.swing.JButton();
        fireAShotHelpBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHelpDisplayArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBody.setBackground(new java.awt.Color(0, 255, 255));
        jpBody.setBorder(new javax.swing.border.MatteBorder(null));

        jpTitle1.setBackground(new java.awt.Color(0, 255, 255));

        jltitle1.setFont(new java.awt.Font("Braggadocio", 1, 24)); // NOI18N
        jltitle1.setForeground(new java.awt.Color(51, 51, 255));
        jltitle1.setText("Battleship - Help");

        javax.swing.GroupLayout jpTitle1Layout = new javax.swing.GroupLayout(jpTitle1);
        jpTitle1.setLayout(jpTitle1Layout);
        jpTitle1Layout.setHorizontalGroup(
            jpTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitle1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jltitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jpTitle1Layout.setVerticalGroup(
            jpTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitle1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpMenuItems.setBackground(new java.awt.Color(0, 255, 255));
        jpMenuItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boardHelpBtn.setText("The Board");
        boardHelpBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                boardHelpBtnActionPerformed(evt);
            }
        });

        playersHelpBtn.setText("Players");
        playersHelpBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                playersHelpBtnActionPerformed(evt);
            }
        });

        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitBtnActionPerformed(evt);
            }
        });

        gamePlayingHelpBtn.setText("Playing");
        gamePlayingHelpBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gamePlayingHelpBtnActionPerformed(evt);
            }
        });

        hitHelpBtn.setText("When Hit");
        hitHelpBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                hitHelpBtnActionPerformed(evt);
            }
        });

        shipHelpBtn.setText("Place Ships");
        shipHelpBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                shipHelpBtnActionPerformed(evt);
            }
        });

        winningHelpBtn.setText("To Win");
        winningHelpBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                winningHelpBtnActionPerformed(evt);
            }
        });

        fireAShotHelpBtn.setText("To Shoot");
        fireAShotHelpBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fireAShotHelpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemsLayout = new javax.swing.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(gamePlayingHelpBtn)
                    .addComponent(playersHelpBtn)
                    .addComponent(boardHelpBtn)
                    .addComponent(hitHelpBtn)
                    .addComponent(fireAShotHelpBtn)
                    .addComponent(shipHelpBtn)
                    .addComponent(winningHelpBtn)
                    .addComponent(quitBtn))
                .addContainerGap())
        );
        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addComponent(gamePlayingHelpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playersHelpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boardHelpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hitHelpBtn)
                .addGap(2, 2, 2)
                .addComponent(fireAShotHelpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipHelpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(winningHelpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setEnabled(false);

        jtHelpDisplayArea.setEditable(false);
        jtHelpDisplayArea.setColumns(20);
        jtHelpDisplayArea.setLineWrap(true);
        jtHelpDisplayArea.setRows(5);
        jtHelpDisplayArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtHelpDisplayArea);

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addComponent(jpTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boardHelpBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boardHelpBtnActionPerformed
    {//GEN-HEADEREND:event_boardHelpBtnActionPerformed
        jtHelpDisplayArea.setText(helpMenuCommands.displayBoardHelp());
    }//GEN-LAST:event_boardHelpBtnActionPerformed

    private void playersHelpBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_playersHelpBtnActionPerformed
    {//GEN-HEADEREND:event_playersHelpBtnActionPerformed
        jtHelpDisplayArea.setText(helpMenuCommands.displayPlayerHelp());        // TODO add your handling code here:
    }//GEN-LAST:event_playersHelpBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitBtnActionPerformed
    {//GEN-HEADEREND:event_quitBtnActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_quitBtnActionPerformed

    private void gamePlayingHelpBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gamePlayingHelpBtnActionPerformed
    {//GEN-HEADEREND:event_gamePlayingHelpBtnActionPerformed
        jtHelpDisplayArea.setText(helpMenuCommands.displayGameHelp());
    }//GEN-LAST:event_gamePlayingHelpBtnActionPerformed

    private void hitHelpBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_hitHelpBtnActionPerformed
    {//GEN-HEADEREND:event_hitHelpBtnActionPerformed
        jtHelpDisplayArea.setText(helpMenuCommands.displayHitHelp());
    }//GEN-LAST:event_hitHelpBtnActionPerformed

    private void shipHelpBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_shipHelpBtnActionPerformed
    {//GEN-HEADEREND:event_shipHelpBtnActionPerformed
        jtHelpDisplayArea.setText(helpMenuCommands.displayShipHelp());
    }//GEN-LAST:event_shipHelpBtnActionPerformed

    private void winningHelpBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_winningHelpBtnActionPerformed
    {//GEN-HEADEREND:event_winningHelpBtnActionPerformed
        jtHelpDisplayArea.setText(helpMenuCommands.displayWinHelp());
    }//GEN-LAST:event_winningHelpBtnActionPerformed

    private void fireAShotHelpBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fireAShotHelpBtnActionPerformed
    {//GEN-HEADEREND:event_fireAShotHelpBtnActionPerformed
        jtHelpDisplayArea.setText(helpMenuCommands.displayShotHelp());
    }//GEN-LAST:event_fireAShotHelpBtnActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boardHelpBtn;
    private javax.swing.JButton fireAShotHelpBtn;
    private javax.swing.JButton gamePlayingHelpBtn;
    private javax.swing.JButton hitHelpBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jltitle1;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpMenuItems;
    private javax.swing.JPanel jpTitle1;
    private javax.swing.JTextArea jtHelpDisplayArea;
    private javax.swing.JButton playersHelpBtn;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton shipHelpBtn;
    private javax.swing.JButton winningHelpBtn;
    // End of variables declaration//GEN-END:variables
}
